/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Windows",
      items: [
        {
          type: "category",
          label: "准备篇",
          items: ["windows/p0/markdown"],
          collapsible: false,
        },
        {
          type: "category",
          label: "基础篇",
          items: ["windows/p1/example"],
          // collapsible: false,
        },
        {
          type: "category",
          label: "进阶篇",
          items: ["windows/p2/example"],
          // collapsible: false,
        },
      ],
      collapsible: false,
    },
    {
      type: "category",
      label: "Mac",
      items: [
        {
          type: "category",
          label: "准备篇",
          items: ["mac/p0/example"],
          collapsible: false,
        },
        {
          type: "category",
          label: "基础篇",
          items: ["mac/p1/example"],
          // collapsible: false,
        },
        {
          type: "category",
          label: "进阶篇",
          items: ["mac/p2/example"],
          // collapsible: false,
        },
      ],
    },
    {
      type: "category",
      label: "项目材料",
      items: ["files/qa","files/contribution", "files/members","files/project-intro"],
      collapsible: false,
    },
  ],
};

module.exports = sidebars;
